import UIKit.UIImage

extension UIImage {
    enum Styles {
        static let vkLogo = UIImage(named: "VK_Blue_Logo")
        static let close = UIImage(named: "close_button")
        static let back = UIImage(named: "back")
        static let check = UIImage(named: "checkmark")
        static let members = UIImage(named: "members")
        static let descriptionOutline = UIImage(named: "description_outline_20")
        static let counterOutline = UIImage(named: "counter_outline_20")
        static let giftOutline = UIImage(named: "gift_outline_20")
        static let newsfeedOutline = UIImage(named: "newsfeed_outline")
        static let profileOutline = UIImage(named: "profile_outline")
        static let qrCodeScanOutline = UIImage(named: "qr_code_scan_outline")
        static let questsOutline = UIImage(named: "quests_outline")
        static let successQuestTreasure = UIImage(named: "success_quest_treasure")
        static let addCircleOutline = UIImage(named: "add_circle_outline")
        static let counterSmall = UIImage(named: "counter_small")
        static let dropdown = UIImage(named: "dropdown")
        static let checkmark = UIImage(named: "checkmark")
        static let add = UIImage(named: "add")
        static let dropdownFlipped = UIImage(named: "dropdown_flipped_16")
        static let remove = UIImage(named: "remove")
        static let minusOutline = UIImage(named: "minus_outline")
        static let plusOutline = UIImage(named: "plus_outline")
        static let moneyOutline = UIImage(named: "money_circle_outline_28")
        static let promocodeOutline = UIImage(named: "promocode_outline_28")
        static let radioOn = UIImage(named: "radio_on_24")
        static let radioOff = UIImage(named: "radio_off_24")
        static let placeOutline = UIImage(named: "place_outline_56")
        static let locationType = UIImage(named: "location_type")
        static let qrCodeType = UIImage(named: "qr_code_type")
        static let questionType = UIImage(named: "question_type")
        static let successMap = UIImage(named: "success_map")
        static let privateQuest = UIImage(named: "private_quest")
        static let chevronDownOutline = UIImage(named: "chevron_down_outline")
        static let chevronUpOutline = UIImage(named: "chevron_up_outline")
        static let doneOutline = UIImage(named: "done_outline")
        static let lockOutline = UIImage(named: "lock_outline")
    }
}
